"use client";

import { useCallback, useEffect, useState } from "react";
import { Archive, LoaderCircle, Pencil, Plus, Shapes } from "lucide-react";
import { toast } from "sonner";

type Category = { id: string; name: string; type: "INCOME" | "EXPENSE"; isSystem: boolean };

export function CategoriesClient() {
  const [items, setItems] = useState<Category[]>([]); const [loading, setLoading] = useState(true);
  const load = useCallback(async () => { setLoading(true); try { const response = await fetch("/api/categories", { cache: "no-store" }); if (!response.ok) throw new Error(); setItems(await response.json()); } catch { toast.error("Kategori gagal dimuat."); } finally { setLoading(false); } }, []);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [load]);
  async function create(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; const data = new FormData(form); const response = await fetch("/api/categories", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: data.get("name"), type: data.get("type") }) }); if (!response.ok) { toast.error("Gagal menambah kategori."); return; } form.reset(); toast.success("Kategori berhasil ditambahkan"); void load(); }
  async function rename(item: Category) { const name = window.prompt("Nama kategori baru", item.name)?.trim(); if (!name || name === item.name) return; const response = await fetch(`/api/categories/${item.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name }) }); if (!response.ok) { toast.error("Kategori sistem tidak dapat diubah."); return; } toast.success("Kategori diperbarui"); void load(); }
  async function archive(item: Category) { if (!window.confirm(`Arsipkan kategori “${item.name}”?`)) return; const response = await fetch(`/api/categories/${item.id}`, { method: "DELETE" }); if (!response.ok) { toast.error("Kategori sistem tidak dapat diarsipkan."); return; } toast.success("Kategori diarsipkan"); void load(); }
  return <div className="grid gap-6 xl:grid-cols-[1fr_340px]">
    <div className="grid gap-6 md:grid-cols-2">{(["EXPENSE", "INCOME"] as const).map((type) => <section key={type} className="rounded-2xl border bg-card p-5"><h2 className="font-heading text-lg font-semibold">{type === "EXPENSE" ? "Pengeluaran" : "Pemasukan"}</h2><div className="mt-4 space-y-2">{loading ? <LoaderCircle className="size-5 animate-spin text-muted-foreground" /> : items.filter((item) => item.type === type).map((item) => <div key={item.id} className="flex min-h-12 items-center gap-3 rounded-xl border px-3"><span className="grid size-8 place-items-center rounded-lg bg-muted"><Shapes className="size-4" /></span><span className="min-w-0 flex-1 truncate text-sm font-medium">{item.name}</span>{item.isSystem ? <span className="text-[10px] uppercase tracking-wide text-muted-foreground">Bawaan</span> : <><button className="tap-target grid place-items-center text-muted-foreground" onClick={() => rename(item)} aria-label={`Ubah ${item.name}`}><Pencil className="size-4" /></button><button className="tap-target grid place-items-center text-muted-foreground hover:text-destructive" onClick={() => archive(item)} aria-label={`Arsipkan ${item.name}`}><Archive className="size-4" /></button></>}</div>)}</div></section>)}</div>
    <form className="h-fit space-y-4 rounded-2xl border bg-card p-5" onSubmit={create}><div><h2 className="font-heading text-lg font-semibold">Kategori baru</h2><p className="mt-1 text-sm text-muted-foreground">Tambahkan kategori personal.</p></div><label className="block space-y-2 text-sm font-medium"><span>Nama</span><input className="h-11 w-full rounded-xl border bg-background px-3" name="name" maxLength={60} required placeholder="Kebutuhan rumah" /></label><label className="block space-y-2 text-sm font-medium"><span>Jenis</span><select className="h-11 w-full rounded-xl border bg-background px-3" name="type"><option value="EXPENSE">Pengeluaran</option><option value="INCOME">Pemasukan</option></select></label><button className="tap-target flex w-full items-center justify-center gap-2 rounded-xl bg-primary font-semibold text-primary-foreground"><Plus className="size-4" />Tambah kategori</button></form>
  </div>;
}
